config/routes.rb
Rails.application.routes.draw do

	devise_for :users, path_names: { 
		sign_up: '' #Stop Sign Up
	}

	root to: "orders#index"
  
 	resources :orders

 	get '/completed' => 'orders#completed_order'
 	get '/cancelled' => 'orders#cancelled_order'
 	get '/follow_up' => 'orders#follow_up'
 	get '/packed' => 'orders#packed_order'
 	get '/pending' => 'orders#pending_order'
 	get '/out_of_stock' => 'orders#out_of_stock'
 	get '/statistics' => 'orders#statistics'
 	get '/returned' => 'orders#returned'
 	get '/not_confrimed' => 'orders#not_confrimed_order'
 	get '/incomplete_order' => 'orders#incomplete_order'
 	get '/delivered' => 'orders#delivered'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!

  def index
    @orders = Order.all
    #@orders_today = Order.where(delivery_date: Date.today, order_status: "Pending")
    @follow_up_orders_today = Order.where(delivery_date: Date.today, order_status: "Follow Up")
  end

  def completed_order
    @orders = Order.where(order_status: "Delivered")
  end

  def cancelled_order
    @orders = Order.where(order_status: "Cancelled")
  end

  def follow_up
    @orders = Order.where(order_status: "Follow Up")
  end

  def packed_order
    @orders = Order.where(order_status: "Packed")
  end

  def pending_order
    @orders = Order.where(order_status: "Pending")
  end

  def out_of_stock
    @orders = Order.where(order_status: "Out of stock")
  end

  def returned
    @orders = Order.where(order_status: "Returned")
  end

  def delivered
    @orders = Order.where(order_status: "Delivered")
  end

  def incomplete_order
    @orders = Order.where(order_status: "Incomplete Order")
  end

  def not_confrimed_order
    @orders = Order.where(order_status: "Not Confrimed")
  end

  def statistics
    
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params.require(:order).permit(:name, :phone, :address, :delivery_date, :product_id, :payment_option,:payment_method, :amount, :order_status, :description, :district))

    if @order.save
      redirect_to orders_path, :notice=> 'Order was successfully created.'
    else
      redirect_to new_order_path, :alert=> 'Error! Please try again'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(params.require(:order).permit(:name, :phone, :address, :delivery_date, :product_id, :payment_option,:payment_method, :amount, :order_status, :description, :district))
      redirect_to :back, :notice=> 'Order was successfully updated.'
    else
      redirect_to new_order_path, :alert=> 'Error! Please try again'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    if @order.destroy
      redirect_to orders_path, :notice => 'Order was successfully deleted.'
    else
      redirect_to orders_path, :alert => 'Error! Please try again'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<% if user_signed_in? %>

<!DOCTYPE html>
  <html>

    <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title><%= yield(:title) %> | BimnepOMS</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application', :media => "all" %>
      <%= stylesheet_link_tag    'print', :media => "print" %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>

    <body class="fixed-nav fixed-nav-basic"> <!-- min sidemenu: mini-navbar-->
    <div id="wrapper">
      <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
          <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
              <div class="dropdown profile-element">
                <span>
                  <h2 style="font-size: 30px; margin-bottom: 20px; color: #f70b0b">BIMNEP <span style="color: #1ab394; font-weight: 900">Ecommerce</span></h2>
                </span>
                <!--<a data-toggle="dropdown" class="dropdown-toggle" href="#">
                  <span class="clear">
                      <span class="block m-t-xs">
                          <strong class="font-bold">RailsOMS Application</strong> <b class="caret"></b>
                      </span>
                  </span>
                </a> 
                <ul class="dropdown-menu animated fadeInRight m-t-xs">
                  <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
                </ul> -->
              </div>
              <div class="logo-element">
                <h2 style="font-size: 10px; margin-top: 0px; margin-bottom: 0px; color: #f70b0b">Bimnep <span style="color: #1ab394; font-weight: 900">Pvt. Ltd</span></h2>
              </div>
            </li>
            <li class="landing_link">
              <%= link_to orders_path do %>
                <i class="fa fa-th-large"></i> <span class="nav-label">Dashboard</span> <span class="label label-warning pull-right">HOME</span></a>
              <% end %>
            </li>
            <li class="active">
              <a href="index.html"><i class="fa fa-shopping-bag"></i> <span class="nav-label">Order</span> <span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li class=""><%= link_to "All Orders", orders_path %></li>
                <li class=""><%= link_to "Completed Orders", completed_path %></li>
                <li class=""><%= link_to "Delivered Orders", delivered_path %></li>
                <li class=""><%= link_to "Cancelled Orders", cancelled_path %></li>
                <li class=""><%= link_to "Follow Up Orders", follow_up_path %></li>
                <li class=""><%= link_to "Packed Orders", packed_path %></li>
                <li class=""><%= link_to "Pending Orders", pending_path %></li>
                <li class=""><%= link_to "Out Of Stock Orders", out_of_stock_path %></li> 
                <li class=""><%= link_to "Returned", returned_path %></li>
                <li class=""><%= link_to "Not Confrimed", not_confrimed_path %></li>
                <li class=""><%= link_to "Incomplete Order", incomplete_order_path %></li>
                <li class=""><%= link_to "Add Order", new_order_path %></li>
                <li class=""><%= link_to "Statistics", statistics_path %></li>
              </ul>
            </li>
            <li>
              <a href="#"><i class="fa fa-cog fa-spin"></i> <span class="nav-label">Profile</span><span class="fa arrow"></span></a>
              <ul class="nav nav-second-level collapse">
                <li><%= link_to "Change Password", edit_user_registration_path %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>

      <div id="page-wrapper" class="gray-bg" style="min-height: 600px;">
        <div class="row border-bottom">
          <nav class="navbar navbar-fixed-top white-bg" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
              <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
              <li>
                <%= link_to statistics_path do %>
                  <span class="btn btn-success">Statistics</span>
                <% end %>
              </li>
              <li>
                <%= link_to new_order_path do  %>
                  <span class="btn btn-primary">New Order</span>
                <% end %>
              </li>
              <li style="padding: 20px 10px">
                <span class="m-r-sm text-muted"><strong>BimnepOMS</strong> Application.</span>
              </li>
              <li class="pull-right">
                <%= link_to destroy_user_session_path, :method => 'delete' do %>
                    <i class="fa fa-sign-out"></i> Log out
                <% end %>
              </li>
            </ul>
          </nav>
        </div>

        <div class="wrapper wrapper-content">

          <% if notice %>
              <div class="alert alert-info">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Notice!</strong> <%= notice %>
              </div>
          <% end %>

          <% if alert %>
              <div class="alert alert-danger">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Alert!</strong> <%= alert %>
              </div>
          <% end %>

          <%= yield %>

        </div>

        <div class="footer">
          <div class="pull-right">
            BY <strong><span style="color: green">Rabin</span><span style="color:red"> Poudyal</span></strong>
          </div>
          <div>
            <strong>Copyright</strong> bimnep.com &copy; <%= Time.now.year %>
          </div>
        </div>
      </div>
    </div>

    <!-- Mainly scripts -->
    <%#= javascript_include_tag 'application' %>

    <!-- Custom and plugin javascript -->
    <script type="text/javascript">
      $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green'
      });
    </script>

    <% if notice %>
      <script>
        $(document).ready(function() {
          setTimeout(function() {
            toastr.options = {
              closeButton: true,
              progressBar: true,
              showMethod: 'slideDown',
              timeOut: 4000
            };
            toastr.success('<%= notice %>', 'Notice');
          }, 1300);
        });
      </script>
    <% end %>

    <script>
      $(document).ready(function(){
        $('.dataTables-example').DataTable({
          dom: '<"html5buttons"B>lTfgitp',
          buttons: [
            { extend: 'copy'},
            {extend: 'csv'},
            {extend: 'excel', title: 'ExampleFile'},
            {extend: 'pdf', title: 'ExampleFile'},

            {extend: 'print',
              customize: function (win){
                $(win.document.body).addClass('white-bg');
                $(win.document.body).css('font-size', '10px');

                $(win.document.body).find('table')
                    .addClass('compact')
                    .css('font-size', 'inherit');
              }
            }
          ]

        });
      });
    </script>

    </body>
  </html>


<% else %>

<!DOCTYPE html>
  <html>

    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <title>Login | BimnepOMS</title>
      <%= csrf_meta_tags %>

      <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application' %>
    </head>

    <body class="gray-bg">
    <div class="middle-box text-center loginscreen animated fadeInDown">
      <div>

        <%= yield %>

      </div>
    </div>

    <div class="footer">
      <div class="pull-right">
        BY <strong><span style="color: green">Rabin</span><span style="color:red"> Poudyal</span></strong>
      </div>
      <div>
        <strong>Copyright</strong> bimnep.com &copy; <%= Time.now.year %>
      </div>
    </div>

    <!-- Mainly scripts -->
    <%= javascript_include_tag 'application' %>

    </body>

  </html>

<% end %>

app/views/orders/cancelled_order.html.erb
<% content_for :title, "Cancelled Orders" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Cancelled Orders Data</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Product</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th width="101px">Actions</th>
              </tr>
            </thead>

            <tbody>

            <% @orders.each do |order| %>

              <tr class="">
                <td><%= order.name %></td>
                <td><%= order.phone %></td>
                <td><%= order.address %><br>-<%= order.district %></td>
                <td><%= order.delivery_date %></td>
                <td><%= order.product_id %></td>
                <td><%= order.payment_option %></td>
                <td><%= order.amount %></td>
                <td><span class="badge badge-primary"> <%= order.order_status %></span>
                  <span class="btn btn-sm btn-white btn-bitbucket" data-toggle="modal" data-target="#myModalUpdate<%= order.id %>" ><span class="fa fa-pencil-square-o"></span></span>
                  <div id="myModalUpdate<%= order.id %>" class="modal fade" role="dialog">
                    <div class="modal-dialog">

                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Update Order Status</h4>
                        </div>
                        <div class="modal-body">
                          <%= form_for(order) do |o| %>
                            <%= o.label :order_status %>
                            <%= o.select :order_status, options_for_select([ ["Pending"],["Cancelled"],["Returned"],["Follow Up"],["Out of stock"], ["Not Confrimed"], ["Packed"], ["Delivered"], ["Incomplete Order"] ], :selected => o.object.order_status), { :class => "btn btn-primary" } %>
                            <%= o.submit "Update", class: "btn btn-primary" %>
                            <%#= o.order_status %>
                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>

                    </div>
                  </div>
                </td>
                <td>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                  <span class="btn btn-white btn-bitbucket" data-toggle="modal" data-target="#myModal_<%= order.id %>" ><span class="fa fa-eye"></span></span>

                  <div id="myModal_<%= order.id %>" class="modal fade" role="dialog">
                    <div class="modal-dialog">

                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Order Details</h4>
                        </div>
                        <div class="modal-body">
                          <h2 class="text-center">Order Status: <b><%= order.order_status %></b></h2>
                          <table width="100%">
                            <tr>
                              <th>Heading</th>
                              <th>Details</th>
                            </tr>
                            <tr>
                              <td>Name</td>
                              <td><%= order.name %></td>
                            </tr>
                            <tr>
                              <td>Order Status</td>
                              <td><%= order.order_status %></td>
                            </tr>
                            <tr>
                              <td>Amount</td>
                              <td><%= order.amount %></td>
                            </tr>
                            <tr>
                              <td>Phone</td>
                              <td><%= order.phone %></td>
                            </tr>
                            <tr>
                              <td>Address</td>
                              <td><%= order.address %></td>
                            </tr>
                            <tr>
                              <td>District</td>
                              <td><%= order.district %></td>
                            </tr>
                            <tr>
                              <td>Delivery Date</td>
                              <td><%= order.delivery_date %></td>
                            </tr>
                            <tr>
                              <td>Product Id</td>
                              <td><%= order.product_id %></td>
                            </tr>
                            <tr>
                              <td>Payment Option</td>
                              <td><%= order.payment_option %></td>
                            </tr>
                            <tr>
                              <td>Payment Method</td>
                              <td><%= order.payment_method %></td>
                            </tr>
                          </table>
                          <h3 class="h4 text-center"><b>Order Description</b></h3><br/>
                          <p><%= order.description %></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>

                    </div>
                  </div>

                </td>
              </tr>

            <% end %>

            </tbody>

            <tfoot>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Product</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/orders/completed_order.html.erb
<% content_for :title, "Completed Orders" %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Completed Orders Data</h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a class="close-link">
            <i class="fa fa-times"></i>
          </a>
        </div>
      </div>
      <div class="ibox-content">

        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Product</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th width="101px">Actions</th>
              </tr>
            </thead>

            <tbody>

            <% @orders.each do |order| %>

              <tr class="">
                <td><%= order.name %></td>
                <td><%= order.phone %></td>
                <td><%= order.address %><br>-<%= order.district %></td>
                <td><%= order.delivery_date %></td>
                <td><%= order.product_id %></td>
                <td><%= order.payment_option %></td>
                <td><%= order.amount %></td>
                <td><span class="badge badge-primary"> <%= order.order_status %></span>
                  <span class="btn btn-sm btn-white btn-bitbucket" data-toggle="modal" data-target="#myModalUpdate<%= order.id %>" ><span class="fa fa-pencil-square-o"></span></span>
                  <div id="myModalUpdate<%= order.id %>" class="modal fade" role="dialog">
                    <div class="modal-dialog">

                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Update Order Status</h4>
                        </div>
                        <div class="modal-body">
                          <%= form_for(order) do |o| %>
                            <%= o.label :order_status %>
                            <%= o.select :order_status, options_for_select([ ["Pending"],["Cancelled"],["Returned"],["Follow Up"],["Out of stock"], ["Not Confrimed"], ["Packed"], ["Delivered"], ["Incomplete Order"] ], :selected => o.object.order_status), { :class => "btn btn-primary" } %>
                            <%= o.submit "Update", class: "btn btn-primary" %>
                            <%#= o.order_status %>
                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>

                    </div>
                  </div>
                </td>
                <td>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to edit_order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                  <% end %>
                  <%= link_to order_path(order.id), :class=>'btn btn-white btn-bitbucket' do %>
                      <i class="fa fa-print" aria-hidden="true"></i>
                  <% end %>
                  <span class="btn btn-white btn-bitbucket" data-toggle="modal" data-target="#myModal_<%= order.id %>" ><span class="fa fa-eye"></span></span>

                  <div id="myModal_<%= order.id %>" class="modal fade" role="dialog">
                    <div class="modal-dialog">

                      <!-- Modal content-->
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                          <h4 class="modal-title">Order Details</h4>
                        </div>
                        <div class="modal-body">
                          <h2 class="text-center">Order Status: <b><%= order.order_status %></b></h2>
                          <table width="100%">
                            <tr>
                              <th>Heading</th>
                              <th>Details</th>
                            </tr>
                            <tr>
                              <td>Name</td>
                              <td><%= order.name %></td>
                            </tr>
                            <tr>
                              <td>Order Status</td>
                              <td><%= order.order_status %></td>
                            </tr>
                            <tr>
                              <td>Amount</td>
                              <td><%= order.amount %></td>
                            </tr>
                            <tr>
                              <td>Phone</td>
                              <td><%= order.phone %></td>
                            </tr>
                            <tr>
                              <td>Address</td>
                              <td><%= order.address %></td>
                            </tr>
                            <tr>
                              <td>District</td>
                              <td><%= order.district %></td>
                            </tr>
                            <tr>
                              <td>Delivery Date</td>
                              <td><%= order.delivery_date %></td>
                            </tr>
                            <tr>
                              <td>Product Id</td>
                              <td><%= order.product_id %></td>
                            </tr>
                            <tr>
                              <td>Payment Option</td>
                              <td><%= order.payment_option %></td>
                            </tr>
                            <tr>
                              <td>Payment Method</td>
                              <td><%= order.payment_method %></td>
                            </tr>
                          </table>
                          <h3 class="h4 text-center"><b>Order Description</b></h3><br/>
                          <p><%= order.description %></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>

                    </div>
                  </div>

                </td>
              </tr>

            <% end %>

            </tbody>

            <tfoot>
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Delivery Date</th>
                <th>Product</th>
                <th>Payment Option</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </tfoot>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<% content_for :title, "Print Order" %>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-8">
    <h2>Invoice</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', orders_path%>
      </li>
      <li class="active">
        <strong>Invoice</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-4">
    <div class="title-action">
      <button href="#" onclick="print_invoice()" class="btn btn-primary"><i class="fa fa-print"></i> Print Invoice </button>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">

    <div class="wrapper wrapper-content animated fadeInRight" id="print">
      <div class="ibox-content p-xl">

        <div class="invoice_head">
          <div class="row">
            <div class="col-xs-10">
              <h2 style="font-size: 30px; margin-bottom: 20px; color: #f70b0b">Bimnep.com <span style="color: #1ab394; font-weight: 900">Online Store</span></h2>
              <p>
                KrishnaGalli, PatanDhoka<br>
                Lalitpur, Nepal
              </p>
            </div>
          </div>
        </div>
        <hr>
        <h4 class="text-center">INVOICE</h4>
        <div class="row">
          <div class="col-xs-6">
            <h5>To:</h5>
            <address>
              <strong><%= @order.name %></strong><br>
              <%= @order.address %><br>
              <%= @order.district %><br>
              <b>Phone :</b> <%= @order.phone %>
            </address>
          </div>

          <div class="col-xs-6 text-right">
            <h4>Invoice No.</h4>
            <h4 class="text-navy">INV-000-<%= @order.id %></h4>
            <p>
              <span><strong>Invoice Date:</strong> Marh 18, 2014</span><br />
              <span><strong>Due Date:</strong> <%= @order.delivery_date %></span>
            </p>
          </div>
        </div>

        <div class="table-responsive m-t">
          <table class="table invoice-table">
            <thead>
            <tr>
              <th>Item List</th>
              <th>Price (Nrs.)</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>
                <div><%= @order.product_id %></div>
              </td>
              <td>Nrs. <%= @order.amount %></td>
            </tr>
            </tbody>
          </table>
        </div><!-- /table-responsive -->

        <hr style="margin-top: 0px;">

        <div class="row">
          <div class="col-xs-6">
            <div class="well m-t">
              <strong>Comments</strong>
              It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less
            </div>
          </div>
          <div class="col-xs-6">
            <table class="table invoice-total">
              <tbody>
              <tr>
                <td><strong>Sub Total :</strong></td>
                <td>Nrs. <%= @order.amount %></td>
              </tr>
              <tr>
                <td><strong>TAX :</strong></td>
                <td>Nrs. 0</td>
              </tr>
              <tr>
                <td><strong>TOTAL :</strong></td>
                <td style="border: 1px solid #DDDDDD;">Nrs. <%= @order.amount %></td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <p>
              Recvied By : __________________
            </p>
          </div>
          <div class="col-xs-6 text-right">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function print_invoice() {
    window.print();
  }
</script>